language: go
go:
 - "1.x"
notifications:
  email:
      - mailme.xu@gmail.com
      
script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled
